# User.create!([
#   {name: "Lewis Z Matos", age: nil, gender: "male", image: "http://graph.facebook.com/1485775778392162/picture", cover: "https://scontent.xx.fbcdn.net/hphotos-xap1/t31.0-8/s720x720/906044_1455612988075108_7604148912649146806_o.jpg", email: "lewm20@gmail.com", encrypted_password: "$2a$10$QwkThQ5MVGIReySdkldtNu3kRYNDxYM.RE/G3UwfsSok5Lss3Aavy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2015-10-22 15:35:49", last_sign_in_at: "2015-10-22 15:08:46", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", provider: "facebook", uid: "1485775778392162"}
# ])

20.times do |i|
  turn = i % 2
	male_images = Dir.glob("#{Rails.root}/app/assets/images/stock_images/male/*.jpg")
  female_images = Dir.glob("#{Rails.root}/app/assets/images/stock_images/female/*.jpg")
  male_female_images = [female_images,male_images]
  array = [FactoryHelper::Name.female_first_name,FactoryHelper::Name.male_first_name]
User.create!([
  {name: array[turn], age: rand(20..50), gender: ["female","male"][turn], image: male_female_images[turn].sample , cover: "https://scontent.xx.fbcdn.net/hphotos-xap1/t31.0-8/s720x720/906044_1455612988075108_7604148912649146806_o.jpg", email: FactoryHelper::Internet.email(array[turn]),password: Devise.friendly_token[0,20], reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2015-10-22 15:35:49", last_sign_in_at: "2015-10-22 15:08:46", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", provider: "facebook", uid: FactoryHelper::Internet.password(10)}
])
end


Event.create!([
  {title: "House of Vans: Television, Viet Cong, Lower Dens", venue: "House of Vans", street_number: 25, street_name: "Franklin Street", city: "Brooklyn", state: "NY", zip: 11222, description: "House of Vans Presents: the final event of the carnival and light-themed series brings brings forth a rare performance by heavyweight New York rock icons Television. Television will be joined by Canadian post-punks Viet Cong and the genre-bending synth-pop of Baltimore's Lower Dens. DJ Brandon Stosuy from Pitchfork will set the vibe of an evening filled with music, art and good times. Guests can keep summer alive with carnival treats, games and prizes, and free beer. ", cost: "free", tickets: "rsvp: https://houseofvansbrooklyn.queueapp.com/events/13097", url: "http://www.vans.com/article_detail/hov-presents-event3.html", image: "/assets/id1-HOV_Presents_Event3_Flyer.jpeg", category: "Concert", date: "2015-10-08", time: "2000-01-01 20:00:00"},
  {title: "The Art of John Lennon 75th Anniversary Exhibition", venue: "AFA Gallery", street_number: 54, street_name: "Green Street", city: "New York", state: "NY", zip: 10013, description: "Opening reception for an exhibition of the extraordinary artworks of John Lennon. All artwork is on exhibition and available for acquisition October 1st through October 31st of 2015. All events are complimentary and open to the public. This presentation is significant in its curation, celebrating the 75th Birthday Anniversary of John Lennon, and will feature programming throughout the exhibition period.", cost: "free", tickets: "rsvp: rsvp@afanyc.com", url: "http://afanyc.com/john-lennon/john-lennon-press-release/", image: "/assets/id2-self-portrait.jpg", category: "Art", date: "2015-10-01", time: "2000-01-01 18:00:00"},
  {title: "Monegraph Release Party", venue: "The New Museum", street_number: 235, street_name: "Bowery Street", city: "New York", state: "NY", zip: 10002, description: "Monegraph is redefining how media will be consumed, created and distributed. We are excited to extend this invitation for you and your guests to join our celebration. This will be a monumental event in history - and the beginning of a media revolution. Exclusive DJ Set: Slava", cost: "free", tickets: "rsvp: https://monegraphreleaseparty.splashthat.com/", url: "https://monegraphreleaseparty.splashthat.com/", image: "/assets/id3-monegraph.png", category: "Art, Party", date: "2015-09-28", time: "2000-01-01 19:30:00"},
  {title: "Fable featuring Blonde Redhead / Prince Rama", venue: "The Knockdown Center", street_number: 52, street_name: "Flushing Ave", city: "Queens", state: "NY", zip: 11378, description: "Filmmaker Derrick Belcham (La Blogotheque, A Story Told Well) and choreographer Emily Terndrup (Sleep No More) present FABLE, a new evening-length production set in Knockdown’s sprawling 50,000-square-foot space. The production features a giant, sound-reactive enclosure that showcases a different, acclaimed musician for each of the six performances, a 360-degree sound environment and an expansive array of transforming light systems from floor to ceiling. In a shifting proscenium, an unpredictable choreographic and theatrical narrative immerses the audience.", cost: "$25.00", tickets: "http://www.ticketweb.com/snl/VenueListings.action?venueId=279334", url: "http://knockdown.center/event/fable/", image: "/assets/id4-fable.jpg", category: "Concert, Art", date: "2015-10-16", time: "2000-01-01 20:00:00"},
  {title: "Fable featuring Skyler Skjelset (Fleet Foxes, Beach House) / Julianna Barwick", venue: "The Knockdown Center", street_number: 52, street_name: "Flushing Ave", city: "Queens", state: "NY", zip: 11378, description: "Filmmaker Derrick Belcham (La Blogotheque, A Story Told Well) and choreographer Emily Terndrup (Sleep No More) present FABLE, a new evening-length production set in Knockdown’s sprawling 50,000-square-foot space. The production features a giant, sound-reactive enclosure that showcases a different, acclaimed musician for each of the six performances, a 360-degree sound environment and an expansive array of transforming light systems from floor to ceiling. In a shifting proscenium, an unpredictable choreographic and theatrical narrative immerses the audience.", cost: "$25.00", tickets: "http://www.ticketweb.com/snl/VenueListings.action?venueId=279334", url: "http://knockdown.center/event/fable/", image: "/assets/id5-fable-box.jpg", category: "Concert, Art", date: "2015-10-17", time: "2000-01-01 20:00:00"},
  {title: "High Line Open Studios", venue: "The High Line, Chelsea", street_number: 526, street_name: "West 26th Street", city: "New York", state: "NY", zip: 10001, description: "The artists of High Line Open Studios invite the public to step inside their private studios during the Fall 2015 art season.  On this self-guided tour, visitors will have exclusive access to private artists' studios based in the heart of the West Chelsea Arts District, where visitors will have access to over 50 private artists' studios in more than 10 buildings. The artists will open their doors to the public on Saturday, Sunday, October 17-18, 2015.  The self guided tour begins at the West Chelsea Arts Building on West 26th Street. Pick up the MAP and event information in the lobbies at 508 and 516 West 26th St.", cost: "free", tickets: "none", url: "http://highlineopenstudios.org/", image: "/assets/id6-HLOS-October2015-6x6.jpeg", category: "Art", date: "2015-10-18", time: "2000-01-01 12:00:00"},
  {title: "NYC Food Film Festival, Tender: Stories of Love and Meat", venue: "AMC Empire 25", street_number: 234, street_name: "West 42nd Street", city: "New York", state: "NY", zip: 10036, description: "Opening night features passionate stories of American meat. Special appearances by renowned Texas pitmasters Scott Morales of Taylor Cafe and Kent Black of Black’s Barbecue from the film, Central Texas Barbecue. Plus pork stories from Maine to Oklahoma, as well as a visit to the Certified Angus Beef test kitchen.VIP party by Hometown BBQ. Including a special performance by the Defibulators! Festival tickets are all-inclusive of food, beverages and entry to film screenings.", cost: "$89", tickets: "http://thefoodfilmfestival.com/2015-nyc-tickets/", url: "http://thefoodfilmfestival.com/opening-night-the-9th-annual-nyc-food-film-festival/", image: "/assets/id7-TENDER-NYC-THUMB.jpg", category: "Film, Food", date: "2015-10-22", time: "2000-01-01 19:00:00"},
  {title: "Laurie Anderson: Habeus Corpus", venue: "Park Avenue Armory", street_number: 643, street_name: "Park Ave", city: "New York", state: "NY", zip: 10065, description: "Former Guantánamo Bay detainee Mohammed el Gharani—imprisoned for seven years beginning when he was just fourteen—is the subject of this new work by iconic musician and performance artist Laurie Anderson. Gharani, who still can't travel to the US despite never having been charged, is live-streamed into the massive Armory drill hall onto a statue that replicates his body. Filling the space is a soundscape originally created by Anderson's late husband Lou Reed, and in the evenings, a musical performance co-created with tUnE-yArDs' Merrill Garbus takes place.", cost: "$15", tickets: "https://commerce.armoryonpark.org/single/PSDetail.aspx?psn=806", url: "http://armoryonpark.org/programs_events/detail/laurie_anderson", image: "/assets/id8-habeas-corpus.jpg", category: "Art", date: "2015-10-02", time: "2000-01-01 20:00:00"}
])
